import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import HeaderBar from '@/components/header-bar';
import { Providers } from '@/shared/providers/providers';
import NotesSidebar from '@/components/notes-sidebar';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { Metadata } from 'next/types';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-auto flex h-screen w-full flex-col bg-background antialiased`}
      >
        <Providers>
          <SidebarProvider>
            <NotesSidebar />
            <SidebarInset>
              <HeaderBar />
              <div className="flex min-h-0 flex-1 flex-col overflow-hidden">{children}</div>
            </SidebarInset>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
